---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - git
    - vim
    - build-essential

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  sudo: yes

- name: Ensure freetds packages are installed
  apt: name={{item}} state=latest
  with_items: freetds-bin

- name: Configure MSSQL connection for freetds driver
  sudo: yes
  template: src=freetds.conf.tpl dest=/etc/freetds/freetds.conf

- name: Copy vim file rc
  sudo: yes
  template: src=.vimrc.tpl dest=/home/vagrant/.vimrc

- name: Copy vim file info
  sudo: yes
  template: src=.viminfo.tpl dest=/home/vagrant/.viminfo

- name: Copy git config
  sudo: yes
  template: src=.gitconfig.tpl dest=/home/vagrant/.gitconfig

# SWAP
- name: 'Create 2Gbs swap file'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "fallocate -l 2G /swapfile"

- name: 'Permissions'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "chmod 600 /swapfile"

- name: 'set up the swap space'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "mkswap /swapfile"

- name: 'enable'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "swapon /swapfile"

- name: 'Check'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "swapon -s"

- name: 'Add to fstab'
  tags: 'Swap'
  become: 'yes'
  become_method: 'sudo'
  shell: "echo '/swapfile none swap sw 0 0' >> /etc/fstab"



