# This viminfo file was generated by Vim 7.4.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Substitute String:
$

# Command Line History (newest to oldest):
:wq
:w
:q!
:qª
:q
:!vagrant box list
:Q
:sudo new /etc/hosts
:pwd
:cd WYSIWYG/
:ls
:cd Code/
:cd ~/Workspace/homestead/
:new
:e
:Wq

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Input Line History (newest to oldest):

# Registers:
"0	CHAR	0
	,
	    "require": {}
"1	LINE	0
	    "require-dev": {
	    "phpunit/phpunit": "~5.0.*" 
	    }
"2	LINE	0
	 # SHELL
"3	CHAR	0
	
	  # Provider-specific configuration so you can fine-tune various
	  # backing providers for Vagrant. These expose provider-specific options.
	  # Example for VirtualBox:
	  #
	  # config.vm.provider "virtualbox" do |vb|
	  #   # Display the VirtualBox GUI when booting the machine
	  #   vb.gui = true
	  #
	  #   # Customize the amount of memory on the VM:
	  #   vb.memory = "1024"
	  # end
	  #
	  # View the documentation for the provider you are using for more
	  # information on available options.
	
	  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
	  # such as FTP and Heroku are also available. See the documentation at
	  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
	  # config.push.define "atlas" do |push|
	  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
	  # end
	
	  # Enable provisioning with a shell script. Additional provisioners such as
	  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	  # documentation for more information about their specific syntax and use.
	  # config.vm.provision "shell", inline: <<-SHELL
	  #   sudo apt-get update
	  #   sudo apt-get install -y apache2
	 
"4	CHAR	0
	
	  # Create a public network, which generally matched to bridged network.
	  # Bridged networks make the machine appear as another physical device on
	  # your network.
	  # config.vm.network "public_network"
	
	  # Share an additional folder to the guest VM. The first argument is
	  # the path on the host to the actual folder. The second argument is
	  # the path on the guest to mount the folder. And the optional third
	  # argument is a set of non-required options.
	 
"5	CHAR	0
	
	  # Disable automatic box update checking. If you disable this, then
	  # boxes will only be checked for updates when the user runs
	  # `vagrant box outdated`. This is not recommended.
	  # config.vm.box_check_update = false
	
	  # Create a forwarded port mapping which allows access to a specific port
	  # within the machine from a port on the host machine. In the example below,
	  # accessing "localhost:8080" will access port 80 on the guest machine.
	  # config.vm.network "forwarded_port", guest: 80, host: 8080
	
	  # Create a private network, which allows host-only access to the machine
	  # using a specific IP.
	 
"6	CHAR	0
	  # The most common coufiguration options are documented and commented below.
	  # For a complete reference, please see the online documentation at
	  # https://docs.vagrantup.com.
	
	  # Every Vagrant development environment requires a box. You can search for
	  # boxes at https://atlas.hashicorp.com/search.
	 
"7	LINE	0
	<?xml version='1.0' encoding='UTF-8'?>
"8	LINE	0
	
"9	LINE	0
	192.168.10.10 homestead.app
	
""-	CHAR	0
	e

# File marks:
'0  8  19  ~/Workspace/homestead/Code/testExample/phpUnitTutorial/Test/StupidTest.php
'1  7  3  ~/Workspace/homestead/Code/testExample/phpunit.xml
'2  13  13  ~/Workspace/homestead/Code/testExample/composer.json
'3  10  4  ~/Workspace/homestead/Code/testExample/composer.json
'4  11  4  ~/Workspace/homestead/Code/testExample/composer.json
'5  11  30  ~/Workspace/homestead/Code/testExample/composer.json
'6  19  3  ~/Workspace/homestead/Code/testExample/composer.json
'7  40  0  ~/.homestead/Homestead.yaml
'8  35  59  ~/.homestead/Homestead.yaml
'9  12  58  ~/Dev/centos/Vagrantfile

# Jumplist (newest first):
-'  8  19  ~/Workspace/homestead/Code/testExample/phpUnitTutorial/Test/StupidTest.php
-'  5  37  ~/Workspace/homestead/Code/testExample/phpUnitTutorial/Test/StupidTest.php
-'  1  0  ~/Workspace/homestead/Code/testExample/phpUnitTutorial/Test/StupidTest.php
-'  7  3  ~/Workspace/homestead/Code/testExample/phpunit.xml
-'  4  0  ~/Workspace/homestead/Code/testExample/phpunit.xml
-'  3  12  ~/Workspace/homestead/Code/testExample/phpunit.xml
-'  1  0  ~/Workspace/homestead/Code/testExample/phpunit.xml
-'  13  13  ~/Workspace/homestead/Code/testExample/composer.json
-'  1  0  ~/Workspace/homestead/Code/testExample/composer.json
-'  10  4  ~/Workspace/homestead/Code/testExample/composer.json
-'  11  4  ~/Workspace/homestead/Code/testExample/composer.json
-'  19  3  ~/Workspace/homestead/Code/testExample/composer.json
-'  40  0  ~/.homestead/Homestead.yaml
-'  1  0  ~/.homestead/Homestead.yaml
-'  35  59  ~/.homestead/Homestead.yaml
-'  12  58  ~/Dev/centos/Vagrantfile
-'  11  60  ~/Dev/centos/Vagrantfile
-'  1  0  ~/Dev/centos/Vagrantfile
-'  10  35  ~/Dev/centos/Vagrantfile
-'  9  0  ~/Dev/centos/Vagrantfile
-'  1  0  /etc/hosts
-'  11  23  /etc/hosts
-'  14  0  /etc/hosts
-'  14  0  ~/Dev/centos/Vagrantfile
-'  21  22  ~/Workspace/fileBrowersApp/bower.json
-'  1  0  ~/Workspace/fileBrowersApp/bower.json
-'  3  23  ~/Workspace/browserPlayer/.bowerrc
-'  1  0  ~/Workspace/browserPlayer/.bowerrc
-'  4  26  ~/.antd/0xe5e0f0d1/tcx/20160525-162539.tcx
-'  1  0  ~/.antd/0xe5e0f0d1/tcx/20160525-162539.tcx
-'  1  0  ~/.antd/0xe5e0f0d1/raw/20160525-162539.tcx
-'  27  0  ~/.antd/0xe5e0f0d1/tcx/20160525-162539.tcx
-'  1  76  /etc/udev/rules.d/99-garmin.rules
-'  32  8  ~/.homestead/Homestead.yaml
-'  33  15  ~/.homestead/Homestead.yaml
-'  21  0  ~/Homestead
-'  9  23  /etc/hosts
-'  30  10  ~/.homestead/Homestead.yaml
-'  8  26  /etc/hosts
-'  11  14  ~/Workspace/WYSIWYG-Laravel-Angular/.env
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/.env
-'  21  27  ~/Workspace/WYSIWYG-Laravel-Angular/public/bower.json
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/public/bower.json
-'  51  0  ~/.homestead/Homestead.yaml
-'  43  0  ~/Workspace/WYSIWYG-Laravel-Angular/database/seeds/ProjectsTableSeeder.php
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/database/seeds/ProjectsTableSeeder.php
-'  39  0  ~/Workspace/WYSIWYG-Laravel-Angular/database/migrations/2016_05_16_174206_create_project_table.php
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/database/migrations/2016_05_16_174206_create_project_table.php
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/package.json
-'  1  0  ~/Workspace/WYSIWYG-Laravel-Angular/gulpfile.js
-'  26  19  ~/Workspace/WYSIWYG-Laravel-Angular/.env
-'  7  21  /etc/hosts
-'  6  21  /etc/hosts
-'  26  10  ~/.homestead/Homestead.yaml
-'  38  14  ~/.homestead/Homestead.yaml
-'  27  31  ~/.homestead/Homestead.yaml
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/.gitignore
-'  24  52  ~/.homestead/Homestead.yaml
-'  1  0  ~/Homestead/Homestead.yaml
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  5  23  /etc/hosts
-'  21  38  ~/.homestead/Homestead.yaml
-'  16  36  ~/.homestead/Homestead.yaml
-'  43  16  ~/.homestead/Homestead.yaml
-'  18  6  ~/.homestead/Homestead.yaml
-'  4  26  /etc/hosts
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  41  16  ~/.homestead/Homestead.yaml
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
-'  1  0  ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
-'  1  0  ~/Homestead/Homestead.yaml
-'  6  24  ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt

# History of marks within files (newest to oldest):

> ~/Workspace/homestead/Code/testExample/phpUnitTutorial/Test/StupidTest.php
	"	8	19
	^	8	20
	.	8	0
	+	6	4
	+	11	0
	+	8	4
	+	10	0
	+	9	20
	+	5	0
	+	8	0

> ~/Workspace/homestead/Code/testExample/phpunit.xml
	"	7	3
	^	7	4
	.	7	3
	+	8	55
	+	3	12
	+	3	0
	+	4	0
	+	5	0
	+	6	0
	+	7	0
	+	8	0
	+	3	3
	+	4	7
	+	5	7
	+	6	3
	+	5	11
	+	6	7
	+	7	3

> ~/Workspace/homestead/Code/testExample/composer.json
	"	13	13
	^	13	14
	.	13	13
	+	17	6
	+	18	15
	+	10	5
	+	10	5
	+	11	0
	+	10	5
	+	11	21
	+	11	0
	+	11	0
	+	10	4
	+	12	17
	+	13	4
	+	16	0
	+	14	8
	+	15	0
	+	14	32
	+	13	13

> ~/.homestead/Homestead.yaml
	"	40	0
	^	35	0
	.	35	0
	+	3	12
	+	13	16
	+	16	0
	+	22	0
	+	20	20
	+	21	38
	+	23	16
	+	24	53
	+	26	23
	+	27	11
	+	26	11
	+	27	32
	+	28	0
	+	27	11
	+	26	11
	+	29	24
	+	30	44
	+	32	22
	+	33	38
	+	30	10
	+	33	15
	+	32	8
	+	36	0
	+	35	0

> /etc/hosts
	"	11	9
	^	11	10
	.	11	9
	+	5	28
	+	4	0
	+	5	0
	+	5	28
	+	5	23
	+	5	28
	+	6	0
	+	6	19
	+	7	21
	+	8	26
	+	18	0
	+	9	0
	+	8	0
	+	9	0
	+	16	0
	+	12	0
	+	11	9

> ~/Dev/centos/Vagrantfile
	"	12	58
	^	12	59
	.	12	59
	+	1	3
	+	7	3
	+	9	22
	+	9	22
	+	9	18
	+	10	2
	+	12	44
	+	1	0
	+	12	49
	+	10	3
	+	10	0
	+	10	0
	+	12	0
	+	14	0
	+	14	0
	+	10	0
	+	9	4
	+	11	3
	+	12	3
	+	10	35
	+	14	0
	+	12	59

> ~/Workspace/fileBrowersApp/bower.json
	"	21	22
	^	21	23
	.	21	22
	+	21	22

> ~/Workspace/browserPlayer/.bowerrc
	"	3	23
	^	3	24
	.	3	23
	+	1	1
	+	2	31
	+	3	23

> ~/.antd/0xe5e0f0d1/tcx/20160525-162539.tcx
	"	4	26
	^	4	27
	.	4	26
	+	1	0
	+	4	26

> ~/.antd/0xe5e0f0d1/raw/20160525-162539.tcx
	"	1	0

> /etc/udev/rules.d/99-garmin.rules
	"	1	76
	^	1	77
	.	1	62
	+	1	62

> ~/Workspace/WYSIWYG-Laravel-Angular/.env
	"	11	14
	^	11	15
	.	11	14
	+	26	19
	+	10	15
	+	11	14
	+	10	15
	+	11	14

> ~/Workspace/WYSIWYG-Laravel-Angular/public/bower.json
	"	21	27
	^	21	28
	.	21	27
	+	22	31
	+	21	27

> ~/Workspace/WYSIWYG-Laravel-Angular/database/seeds/ProjectsTableSeeder.php
	"	43	0
	^	43	1
	.	20	57
	+	1	1
	+	18	34
	+	19	45
	+	20	57

> ~/Workspace/WYSIWYG-Laravel-Angular/database/migrations/2016_05_16_174206_create_project_table.php
	"	39	0

> ~/Workspace/WYSIWYG-Laravel-Angular/package.json
	"	1	0

> ~/Workspace/WYSIWYG-Laravel-Angular/gulpfile.js
	"	1	0

> ~/Workspace/homestead/Code/LaravelAngularSPA/.gitignore
	"	1	0

> ~/Homestead/Homestead.yaml
	"	1	0

> ~/Workspace/homestead/Code/LaravelAngularSPA/README.txt
	"	6	24
	^	6	25
	.	6	24
	+	3	76
	+	6	24

> ~/Workspace/homestead/Code/LaravelAngularSPA/README.tct
	"	1	0
